VARIABLE MY_ASWI VARCHAR2(10);
EXEC :MY_ASWI:='[^0-9.]';
--TO FIND THE HIGHEST AMOUNT DEBITED FROM THE BANK EACH YEAR
SELECT EXTRACT(YEAR FROM "DATE") AS YEAR, MAX(CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MY_ASWI,'') AS NUMBER))AS HIGHESTDEBITEDAMOUNT FROM BANK_TRANSACTION
WHERE WITHDRAWAL_AMT IS NOT NULL GROUP BY EXTRACT(YEAR FROM "DATE") ORDER BY EXTRACT(YEAR FROM "DATE") ASC;
--TO FIND THE LOWEST AMOUNT DEBITED FROM THE BANK IN EACH YEAR --
SELECT EXTRACT(YEAR FROM "DATE") AS YEAR, MIN(CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MY_ASWI,'')AS NUMBER)) AS LOWESTDEBITEDAMOUNT FROM BANK_TRANSACTION
WHERE WITHDRAWAL_AMT IS NOT NULL GROUP BY EXTRACT(YEAR FROM "DATE") ORDER BY EXTRACT(YEAR FROM "DATE") ASC;
--TO FIND THE 5TH HIGHEST WITHDRAWAL AMOUNT AT EACH YEAR--
SELECT YEAR, FIFTHHIGHESTAMOUNT FROM(SELECT EXTRACT(YEAR FROM "DATE") AS YEAR,CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MY_ASWI,'')AS NUMBER) AS FIFTHHIGHESTAMOUNT,DENSE_RANK() OVER(PARTITION BY EXTRACT(YEAR FROM "DATE") ORDER BY
CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MY_ASWI,'') AS NUMBER)DESC) AS R FROM BANK_TRANSACTION WHERE CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MY_ASWI,'')AS NUMBER) IS NOT NULL) WHERE R = 5;
--TO COUNT THE WITHDEAWAL TRANSACTION BETWEEN MAY 5, 2018,AND MARCH 7,2019--
SELECT COUNT(CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MY_ASWI,'')AS NUMBER)) AS WITH_DRAWAL_COUNT FROM BANK_TRANSACTION
WHERE "DATE" BETWEEN TO_DATE('05-05-2018', 'DD-MM-YYYY')AND TO_DATE('07-03-2019', 'DD-MM-YYYY');
--The First five largest Withdrawal transactions are Occured in year 18 --
sELECT DISTINCT EXTRACT(YEAR FROM "DATE") AS Year,CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MY_ASWI, '') AS NUMBER) AS Largest_With_drawal FROM BANK_TRANSACTION WHERE EXTRACT(YEAR FROM "DATE") = 2018 AND
CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MY_ASWI, '') AS NUMBER) IS NOT NULL ORDER BY CAST(REGEXP_REPLACE(WITHDRAWAL_AMT, :MY_ASWI, '') AS NUMBER) DESC FETCH FIRST 5 ROWS ONLY;