--Answers--

VARIABLE MYCONSTANT VARCHAR2(10);
EXEC :MYCONSTANT:='[^0-9.]';
--Answer for first query C
SELECT EXTRACT(YEAR FROM "DATE") AS YEAR,
MAX(CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MYCONSTANT,'') AS NUMBER)) AS HighestDebiteddAmount
FROM BANK_TRANSACTION
WHERE WITHDRAWAL_AMT IS NOT NULL 
GROUP BY EXTRACT(YEAR FROM "DATE") ORDER BY EXTRACT(YEAR FROM "DATE") ASC;

--answer for second qury C
SELECT EXTRACT (YEAR FROM "DATE") AS YEAR,
MAX(CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MYCONSTANT,'') AS NUMBER)) AS LOWESTDEBITEDEDAMOUNT
FROM BANK_TRANSACTIONWHERE WITHDRAWAL_AMT IS NOT NULL
GROUP BY EXTRACT (YEAR FROM "DATE") ORDER BY EXTARCT (YEAR FROM "DATE") ASC;

-- answer for third query C

SELECT , FIFTH_HIGHEST_AMOUNT
FROM(
    SELECT EXTRACT (YEAR FROM "DATE") AS YEAR,
    CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MYCONSTANT,'') AS NUMBER )AS FIFTHHIGHESTAMOUNT
    DENSE_RANK()OVER(PARTITION BY EXTRACT (YEAR FROM "DATE") ORDER BY
     CAST REGEXP_REPLACE(WITHDRAWAL_AMT,:MYCONSTANT,'') AS NUMBER ) DESC) AS R
     FROM BANK_TRANSACTION
     WHERE CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MYCONSTANT,'') AS NUMBER ) IS NOT NULL
)
WHERE R= 5;

--Answer for fourth query C

SELECT COUNT (CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MYCONSTANT,'') AS NUMBER)) AS With_drawal_Count
FROM BANK_TRANSACTION
WHERE "DATE" BETWEEN TO_DATE ('05-05-2018', 'DD-MM-YYYY') AND  TO_DATE('07-03-2019', 'DD-MM-YYYY');


-- Answer for fifth query C

SELECT DISTINCT EXTRACT (YEAR FROM "DATE") AS YEAR
CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MYCONSTANT,'') AS NUMBER ) AS Largest_Withdrawal
FROM BANK_TRANSACTION
WHERE EXTRACT (YEAR FROM "DATE") =2018 AND
CAST(REGEXP_REPALCE(WITHDRAWAL_AMT,'[^0-9.]','') AS NUMBER IS NOT NULL
ORDER BY CAST (REGEXP_REPLACE(WITHDRAWAL_AMT,:MYCONSTANT,'') AS NUMBER ) DESC
FETCH FIRST 5 ROWS ONLY;

---  Sucessfully completed 
