VARIABLE MY_VAR VARCHAR2(10);
EXEC :MY_VAR:='[^0-9.]';


SELECT EXTRACT(YEAR FROM "DATE") AS YEAR,
MAX(CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MY_VAR,'') AS NUMBER)) AS HIGHESTDEBITEDAMOUNT FROM BANK_TRANSACTION
WHERE WITHDRAWAL_AMT IS NOT NULL GROUP BY EXTRACT(YEAR FROM "DATE") ORDER BY EXTRACT(YEAR FROM "DATE") ASC;



SELECT EXTRACT(YEAR FROM "DATE") AS YEAR,
MIN(CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MY_VAR,'') AS NUMBER)) AS LOWESTDEBITEDAMOUNT FROM BANK_TRANSACTION
WHERE WITHDRAWAL_AMT IS NOT NULL GROUP BY EXTRACT(YEAR FROM "DATE") ORDER BY EXTRACT(YEAR FROM "DATE") ASC;




SELECT YEAR,FIFTHHIGHESTAMOUNT
FROM(
        SELECT EXTRACT(YEAR FROM "DATE") AS YEAR,CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MY_VAR,'') AS NUMBER) AS   FIFTHHIGHESTAMOUNT,  
        DENSE_RANK() OVER (PARTITION BY EXTRACT(YEAR FROM "DATE") ORDER BY CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MY_VAR,'') AS NUMBER) DESC) AS R 
        FROM BANK_TRANSACTION WHERE CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MY_VAR,'') AS NUMBER) IS NOT NULL
    )WHERE R=5;

SELECT COUNT (CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MY_VAR,'') AS NUMBER)) AS WITH_DRAWAL_COUNT FROM BANK_TRANSACTION WHERE "DATE" BETWEEN TO_DATE('05-05-2018','DD-MM-YYYY') AND TO_DATE('07-03-2019','DD-MM-YYYY');




SELECT DISTINCT EXTRACT(YEAR FROM "DATE") AS YEAR,
CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MY_VAR,'') AS NUMBER) AS LARGEST_WITHDRAWAL FROM BANK_TRANSACTION W
HERE EXTRACT(YEAR FROM "DATE")=2018  AND CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MY_VAR,'') AS NUMBER) IS NOT NULL ORDER BY CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MY_VAR,'') AS NUMBER) 
DESC FETCH FIRST 5 ROWS ONLY;
