/* To Find the Highest amount Debited from the bank in each year */
select * FROM BANK_TRANSACTION;
SELECT EXTRACT(YEAR FROM "DATE") AS Year,
MAX(CAST(REGEXP_REPLACE(WITHDRAWAL_AMT, '[^0-9.]', '') AS NUMBER)) AS
HighestDebitedAmount
FROM WITHDRAW_Q
WHERE WITHDRAWAL_AMT IS NOT NULL
GROUP BY EXTRACT(YEAR FROM "DATE");


/*To Find the Lowest amount Debited from the bank in each year */

SELECT EXTRACT(YEAR FROM "DATE") AS Year,
MIN(CAST(REGEXP_REPLACE(WITHDRAWAL_AMT, '[^0-9.]', '') AS NUMBER)) AS
LowestDebitedAmount
FROM BANK_TRANSACTION
WHERE WITHDRAWAL_AMT IS NOT NULL
GROUP BY EXTRACT(YEAR FROM "DATE");


/*to Find the 5th highest Withdrawal amount at each year */

SELECT Year, FifthHighestAmount
 FROM (
SELECT
EXTRACT(YEAR FROM "DATE") AS Year,
CAST(REGEXP_REPLACE(WITHDRAWAL_AMT, '[^0-9.]', '') AS NUMBER) AS
FifthHighestAmount,
DENSE_RANK() OVER (PARTITION BY EXTRACT(YEAR FROM "DATE") ORDER BY
CAST(REGEXP_REPLACE(WITHDRAWAL_AMT, '[^0-9.]', '') AS NUMBER) DESC ) AS R
FROM BANK_TRANSACTION
WHERE CAST(REGEXP_REPLACE(WITHDRAWAL_AMT, '[^0-9.]', '') AS NUMBER) IS
NOT NULL
)
WHERE R = 5;


/* to count the withdrawal transactions between May 5, 2018, and March 7,2019 */

SELECT COUNT(CAST(REGEXP_REPLACE(WITHDRAWAL_AMT, '[^0-9.]', '') AS
NUMBER)) AS With_drawal_Count
FROM BANK_TRANSACTION
WHERE "DATE" BETWEEN TO_DATE('05-05-2018', 'DD-MM-YYYY') AND TO_DATE('07-
03-2019', 'DD-MM-YYYY');

/* to Find the First five largest Withdrawal transactions are Occured in year 18 */

SELECT DISTINCT EXTRACT(YEAR FROM "DATE") AS Year,
CAST(REGEXP_REPLACE(WITHDRAWAL_AMT, '[^0-9.]', '') AS NUMBER) AS
Largest_With_drawal
FROM BANK_TRANSACTION
WHERE EXTRACT(YEAR FROM "DATE") = 2018 AND
CAST(REGEXP_REPLACE(WITHDRAWAL_AMT, '[^0-9.]', '') AS NUMBER) IS NOT NULL
ORDER BY CAST(REGEXP_REPLACE(WITHDRAWAL_AMT, '[^0-9.]', '') AS NUMBER)
DESC FETCH FIRST 5 ROWS ONLY;