<<<<<<< HEAD
VARIABLE MYCONSTANT1 VARCHAR2(10);
EXEC :MYCONSTANT1:='[^0-9.]';



SELECT EXTRACT(YEAR FROM "DATE") AS YEAR,
MAX(CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MYCONSTANT1,'') AS NUMBER)) AS HIGHESTDEBITEDAMOUNT
FROM BANK_TRANSACTION
WHERE WITHDRAWAL_AMT IS NOT NULL
GROUP BY EXTRACT(YEAR FROM "DATE") ORDER BY EXTRACT(YEAR FROM "DATE") ASC;



SELECT EXTRACT(YEAR FROM "DATE") AS YEAR,
MIN(CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MYCONSTANT1,'') AS NUMBER)) AS LOWESTDEBITEDAMOUNT
=======
VARIABLE MYCONSTANT VARCHAR2(10);
EXEC :MYCONSTANT:='[^0-9.]';

SELECT EXTRACT(YEAR FROM "DATE") AS YEAR,
MAX(CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MYCONSTANT, '') AS NUMBER)) AS
HIGHESTDEBITEDAMOUNT
FROM BANK_TRANSACTION
WHERE WITHDRAWAL_AMT IS NOT NULL
GROUP BY EXTRACT(YEAR FROM "DATE") ORDER BY EXTRACT(YEAR FROM "DATE") ASC;


SELECT EXTRACT(YEAR FROM "DATE") AS YEAR,
MIN(CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MYCONSTANT, '') AS NUMBER)) AS
LOWESTDEBITEDAMOUNT
>>>>>>> 857c8f0654c97f0f8a83c72c3c64558b9bce6eb0
FROM BANK_TRANSACTION
WHERE WITHDRAWAL_AMT IS NOT NULL
GROUP BY EXTRACT(YEAR FROM "DATE") ORDER BY EXTRACT(YEAR FROM "DATE") ASC;


<<<<<<< HEAD

SELECT YEAR,FIFTHHIGHESTAMOUNT
FROM(
    SELECT EXTRACT(YEAR FROM "DATE") AS YEAR,
    CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MYCONSTANT1,'') AS NUMBER) AS FIFTHHIGHESTAMOUNT,
    DENSE_RANK() OVER (PARTITION BY EXTRACT(YEAR FROM "DATE") ORDER BY
    CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MYCONSTANT1,'') AS NUMBER) DESC) AS R
    FROM BANK_TRANSACTION
    WHERE CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MYCONSTANT1,'') AS NUMBER) IS NOT NULL
=======
SELECT YEAR , FIFTHHIGHESTAMOUNT
FROM (
SELECT
EXTRACT(YEAR FROM "DATE") AS YEAR,
CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MYCONSTANT, '') AS NUMBER) AS
FIFTHHIGHESTAMOUNT,
DENSE_RANK() OVER (PARTITION BY EXTRACT(YEAR FROM "DATE") ORDER BY
CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MYCONSTANT, '') AS NUMBER) DESC ) AS R
FROM BANK_TRANSACTION
WHERE CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MYCONSTANT, '') AS NUMBER) IS
NOT NULL
>>>>>>> 857c8f0654c97f0f8a83c72c3c64558b9bce6eb0
)
WHERE R=5;


<<<<<<< HEAD
=======
SELECT COUNT(CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MYCONSTANT, '') AS
NUMBER)) AS WITH_DRAWAL_COUNT
FROM BANK_TRANSACTION
WHERE "DATE" BETWEEN TO_DATE('05-05-2018', 'DD-MM-YYYY') AND TO_DATE('07-03-2019', 'DD-MM-YYYY');
>>>>>>> 857c8f0654c97f0f8a83c72c3c64558b9bce6eb0

SELECT COUNT(CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MYCONSTANT1,'') AS NUMBER)) AS WITH_DRAWAL_COUNT
FROM BANK_TRANSACTION
WHERE "DATE" BETWEEN TO_DATE('05-05-2018','DD-MM-YYYY') AND TO_DATE('07-03-2019','DD-MM-YYYY');

SELECT DISTINCT EXTRACT(YEAR FROM "DATE") AS YEAR,
<<<<<<< HEAD
CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MYCONSTANT1,'') AS NUMBER) AS LARGEST_WITHDRAWAL
FROM BANK_TRANSACTION
WHERE EXTRACT(YEAR FROM "DATE")=2018 AND
CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MYCONSTANT1,'') AS NUMBER) IS NOT NULL
ORDER BY CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MYCONSTANT1,'') AS NUMBER) DESC
FETCH FIRST 5 ROWS ONLY;
=======
CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MYCONSTANT, '') AS NUMBER) AS
LARGEST_WITH_DRAWAL
FROM BANK_TRANSACTION
WHERE EXTRACT(YEAR FROM "DATE") = 2018 AND
CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MYCONSTANT, '') AS NUMBER) IS NOT NULL
ORDER BY CAST(REGEXP_REPLACE(WITHDRAWAL_AMT,:MYCONSTANT, '') AS NUMBER)
DESC FETCH FIRST 5 ROWS ONLY;
>>>>>>> 857c8f0654c97f0f8a83c72c3c64558b9bce6eb0
